import path from 'path';
import fs from 'fs';

const cutsDir = path.join(process.cwd(), 'public/images/cuts');
const outputFile = path.join(process.cwd(), 'src/data/cuts.ts');

interface CutFile {
    index: number;
    filename: string;
    type: 'video' | 'image';
}

function generateCuts(): CutFile[] {
    if (!fs.existsSync(cutsDir)) {
        console.warn(`Warning: Cuts directory not found at ${cutsDir}`);
        return [];
    }

    const cuts: CutFile[] = [];
    const files = fs.readdirSync(cutsDir);

    for (const file of files) {
        // Match files like 0.mp4, 1.webp, 2.mp4, etc.
        const match = file.match(/^(\d+)\.(mp4|webp)$/i);
        if (!match) {
            continue;
        }

        const index = parseInt(match[1], 10);
        const extension = match[2].toLowerCase();
        const type = extension === 'mp4' ? 'video' : 'image';

        cuts.push({
            index,
            filename: file,
            type
        });
    }

    // Sort by index
    cuts.sort((a, b) => a.index - b.index);

    return cuts;
}

function generateCutsFile(cuts: CutFile[]): string {
    const cutsString = cuts
        .map(cut => `    {
        index: ${cut.index},
        filename: "${cut.filename}",
        type: "${cut.type}"
    }`)
        .join(',\n');

    return `// This file is auto-generated by scripts/generate-cuts.ts
// Do not edit manually - run "npm run generate:cuts" to regenerate

export interface CutFile {
    index: number;
    filename: string;
    type: 'video' | 'image';
}

export const cuts: CutFile[] = [
${cutsString}
];

// Helper function to get cut path
export const getCutPath = (filename: string): string => {
    return \`/images/cuts/\${filename}\`;
}; // By John Michael
`;
}

function main() {
    try {
        console.log('Generating cuts from file system...');
        const cuts = generateCuts();

        if (cuts.length === 0) {
            console.error('Error: No cuts found!');
            process.exit(1);
        }

        // Ensure the output directory exists
        const outputDir = path.dirname(outputFile);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
            console.log(`✓ Created directory: ${outputDir}`);
        }

        const content = generateCutsFile(cuts);
        fs.writeFileSync(outputFile, content, 'utf-8');

        console.log(`✓ Successfully generated ${cuts.length} cuts:`);
        cuts.forEach(cut => {
            console.log(`  - ${cut.index}: ${cut.filename} (${cut.type})`);
        });
        console.log(`✓ Written to ${outputFile}`);
    } catch (error) {
        console.error('Error generating cuts:', error);
        process.exit(1);
    }
}
main(); // By John Michael