import fs from 'fs';
import path from 'path';

const albumsDir = path.join(process.cwd(), 'public/images/albums');
const outputFile = path.join(process.cwd(), 'src/data/photos.ts');

interface Album {
    id: string;
    name: string;
    photoCount: number;
}

function generateAlbums(): Album[] {
    if (!fs.existsSync(albumsDir)) {
        console.warn(`Warning: Albums directory not found at ${albumsDir}`);
        return [];
    }

    const albums: Album[] = [];
    const entries = fs.readdirSync(albumsDir, { withFileTypes: true });

    for (const entry of entries) {
        if (!entry.isDirectory()) {
            continue;
        }

        const albumId = entry.name;
        const albumPath = path.join(albumsDir, albumId);
        
        // Count .webp files in the album directory
        const files = fs.readdirSync(albumPath)
            .filter(file => file.endsWith('.webp'))
            .map(file => {
                const match = file.match(/^(\d+)\.webp$/);
                return match ? parseInt(match[1], 10) : null;
            })
            .filter((num): num is number => num !== null)
            .sort((a, b) => a - b);

        const photoCount = files.length;

        if (photoCount === 0) {
            console.warn(`Warning: Album "${albumId}" has no images, skipping`);
            continue;
        }

        albums.push({
            id: albumId,
            name: albumId, // Keep original ID as name for consistency
            photoCount
        });
    }

    // Sort albums alphabetically by ID
    albums.sort((a, b) => a.id.localeCompare(b.id));

    return albums;
}

function generatePhotosFile(albums: Album[]): string {
    // Format albums array without quotes around keys for cleaner TypeScript
    const albumsString = albums
        .map(album => `    {
        id: "${album.id}",
        name: "${album.name}",
        photoCount: ${album.photoCount}
    }`)
        .join(',\n');

    return `// This file is auto-generated by scripts/generate-albums.ts
// Do not edit manually - run "npm run generate:albums" to regenerate

export interface Album {
    id: string;
    name: string;
    photoCount: number;
}

// Albums in alphabetical order (left to right, top to bottom)
export const albums: Album[] = [
${albumsString}
];

// Helper function to generate image path
export const getImagePath = (albumId: string, index: number): string => {
    return \`/images/albums/\${albumId}/\${index}.webp\`;
};

// Helper function to get album cover (index 0)
export const getAlbumCover = (albumId: string): string => {
    return getImagePath(albumId, 0);
};

// Legacy exports for backward compatibility (can be removed after migration)
export const photoCollections = albums;
export const photoData: any[] = []; // Deprecated - use dynamic paths instead
`;
}

function main() {
    try {
        console.log('Generating albums from file system...');
        const albums = generateAlbums();

        if (albums.length === 0) {
            console.error('Error: No albums found!');
            process.exit(1);
        }

        const content = generatePhotosFile(albums);
        fs.writeFileSync(outputFile, content, 'utf-8');

        console.log(`✓ Successfully generated ${albums.length} albums:`);
        albums.forEach(album => {
            console.log(`  - ${album.id}: ${album.photoCount} photos`);
        });
        console.log(`✓ Written to ${outputFile}`);
    } catch (error) {
        console.error('Error generating albums:', error);
        process.exit(1);
    }
}
main(); // By John Michael
