// This file is auto-generated by scripts/generate-albums.ts
// Do not edit manually - run "npm run generate:albums" to regenerate

export interface Album {
    id: string;
    name: string;
    photoCount: number;
}

// Albums in alphabetical order (left to right, top to bottom)
export const albums: Album[] = [
    {
        id: "midnight",
        name: "midnight",
        photoCount: 18
    },
    {
        id: "mum",
        name: "mum",
        photoCount: 5
    },
    {
        id: "oceanside",
        name: "oceanside",
        photoCount: 27
    },
    {
        id: "phoenix",
        name: "phoenix",
        photoCount: 5
    },
    {
        id: "springtober",
        name: "springtober",
        photoCount: 10
    },
    {
        id: "ultra-sodade",
        name: "ultra-sodade",
        photoCount: 10
    }
];

// Helper function to generate image path
export const getImagePath = (albumId: string, index: number): string => {
    return `/images/albums/${albumId}/${index}.webp`;
};

// Helper function to get album cover (index 0)
export const getAlbumCover = (albumId: string): string => {
    return getImagePath(albumId, 0);
};

// Legacy exports for backward compatibility (can be removed after migration)
export const photoCollections = albums;
export const photoData: any[] = []; // Deprecated - use dynamic paths instead
